### ISSUE TITLE
How to use nova_get_settings helper in other config files

### ISSUE THREAD

**Issue by mikhi** [optimistdigital/nova-settings#95]
Hi,

It is possible to use nova_get_settings() outside nova? i.e. in other config files?

Thanks,
Mihai

**Comment by Tarpsvo** [comment]
Hi!

It cannot be done inside config files because the settings are stored in MySQL and requires querying the database.

The database connection info is inside the config files, so you would essentially be trying to query the database with no config.

The best you could do is modify the config inside AppServiceProvider boot() or register() methods.
